### ISSUE TITLE
[DOCS] Clarify boltdb configuration

### ISSUE THREAD

**Issue by rustatian** [spiral/roadrunner-binary#101]
We should update comments used in the `boltdb` docs (kv + jobs) to not confuse users about `file` field. We removed `dir` for the path and use the file with dir together like `/home/user/some/path/to/rr.db`.
link: https://github.com/spiral/roadrunner-plugins/issues/39

**Comment by Shikachuu** [comment]
Hey @rustatian, since I was the root-cause I proposed changes to the docs with a PR.
[Docs PR 74](https://github.com/spiral/roadrunner-docs/pull/74)

**Comment by rustatian** [comment]
fixed by: https://github.com/spiral/roadrunner-docs/pull/74
