### ISSUE TITLE
[BUG] v2.5.0 binary for linux

### ISSUE THREAD

**Issue by cappuc** [spiral/roadrunner-binary#118]
I tried this code:

```sh
./vendor/bin/rr get-binary
```

On first run it gave this warning and downloaded v2.4.2: 

```
Environment:
   - Version:          2.*
   - Stability:        stable
   - Operating System: linux
   - Architecture:     amd64
 
 [WARNING] unknown/unknown v2.5.0 does not contain available assembly (further search in progress)
```

On next runs the warning disappeared and it downloaded v2.5.0 but when running `rr` it gives this error: `sh: ./rr: not found`.

I tested it on alpine linux inside docker container

**Comment by cappuc** [comment]
With `2.5.0-beta.2` it works
With `2.5.0-rc.1` and `2.5.0-rc.2` it gives the same error: `sh: ./rr: not found`

**Comment by cappuc** [comment]
./vendor/bin/rr --version
RoadRunner CLI 2.5.0

**Comment by rustatian** [comment]
You need to do `chmod +x rr`

**Comment by rustatian** [comment]
> > For the alpine, please, use the musl version: https://github.com/spiral/roadrunner-binary/releases/download/v2.5.0/roadrunner-2.5.0-unknown-musl-amd64.zip
> 
> 
> 
> Without installing `libc6-compat` it doesn't work

Yeah, because it's not a full static build. Go needs to link some OS libs for the user/net packages (and some other). I just wanted to say, that for the alpine we have a different binary.
