### ISSUE TITLE
[BUG] RR v2.6.5 is taking roadrunner-plugins v2.7.0-alpha.1

### ISSUE THREAD

**Issue by vladimir-vv** [spiral/roadrunner-binary#151]
Could you please update dependency github.com/spiral/roadrunner-plugins/v2
RR v2.6.5 is taking roadrunner-plugins v2.7.0-alpha.1 (without latest changes)

Thank you 🙏

**Comment by rustatian** [comment]
Hey @vladimir-vv , after the stable version is released, RR is supported in the `stable` branch until the next stable minor version. So, `stable` branch will not receive 2.7.x updates, only 2.6.x -> https://github.com/spiral/roadrunner-binary/blob/stable/go.mod#L18

**Comment by vladimir-vv** [comment]
Got it, thank you. Just didn't understand why we didn't see the metric rr_http_requests_queue with gauge type 
It was in changes for v2.6.5:
"Fix: wrong metrics type for the rr_http_requests_queue"

**Comment by rustatian** [comment]
@vladimir-vv That was a problem when cherry-picking a particular commit. The `master` branch contains the latest and not released yet features.
I've released the fixed version: https://github.com/spiral/roadrunner-binary/releases/tag/v2.6.6, sorry for the inconvenience.

**Comment by vladimir-vv** [comment]
Thank you! Works as expected.
