### ISSUE TITLE
[ARCH] Current architecture (arm64) may not be supported

### ISSUE THREAD

**Issue by sc0rp10** [spiral/roadrunner-binary#16]
Hi, tried to install roadrunner on latest Apple macbook with Apple Silicon M1 processor but installation failed with the message:

```
Uncaught OutOfRangeException: Current architecture (arm64) may not be supported in vendor/spiral/roadrunner-cli/src/Environment/Architecture/Factory.php:56
```

It would be nice if roadrunner will support arm64 architecture and will have precompiled binaries for it.

Thanks!

**Comment by 48d90782** [comment]
Hi @sc0rp10, nice to meet you. Yeah, I agree,  we will provide a binary for the macOS arm64.

**Comment by 48d90782** [comment]
@sc0rp10 Feel free to try the M1 builds https://github.com/spiral/roadrunner-binary/releases/tag/v2.0.2-beta.2

**Comment by n7olkachev** [comment]
@48d90782 docker for mac on m1 uses linux/arm64 (with fallback to linux/amd64). Could you also provide arm64 docker image?

**Comment by 48d90782** [comment]
@n7olkachev For sure, could you please create a ticket in the `roadrunner-binary` repository fo it?

**Comment by n7olkachev** [comment]
Done #19

**Comment by 48d90782** [comment]
@n7olkachev Now in the v2.0.4, darwin/arm64 docker container, feel free to try)
