### ISSUE TITLE
[DOCS] Update repository readme file

### ISSUE THREAD

**Issue by tarampampam** [spiral/roadrunner-binary#27]
The readme file in this repository needs to be updated. I mean:

- Add information about "what is this and for a what?"
- How to make changes to existing code, how to write and add plugins
- How to run the application, what sub-commands and flags are available
- Links to relevant repositories with [php-worker](https://github.com/spiral/roadrunner-worker), [roadrunner core](https://github.com/spiral/roadrunner), etc
- Description of the configuration process

@48d90782 What do you think?

**Comment by 48d90782** [comment]
@tarampampam We have one source for the documentation. This is the roadrunner.dev site backed by the roadrunner-docs GitHub repository. I suppose, that we can put some explanation links here, where to find relative information (php-worker, roadrunner-core, etc). But most of these points are covered by the roadrunner.dev documentation except for the detailed information about new commands.
