### ISSUE TITLE
[ARCH] Linux (arm64) is not supported

### ISSUE THREAD

**Issue by adhasahar97** [spiral/roadrunner-binary#38]
Tried to install Roadrunner linux ubuntu 20.04 (arm64) and it throws 
```
Uncaught OutOfRangeException: Current architecture (arm64) may not be supported in vendor/spiral/roadrunner-cli/src/Environment/Architecture/Factory.php:56
```
I'm using AWS latest gen m6g instance which is based on arm arch

**Comment by wolfy-j** [comment]
Reference https://github.com/spiral/roadrunner-cli/pull/5
