### ISSUE TITLE
[BUG] .env handling broken in 2.0.4?

### ISSUE THREAD

**Issue by taylorotwell** [spiral/roadrunner-binary#41]
Hello,

After 2.0.4 we are seeing our Laravel `.env` file variables persist forever in Laravel Octane powered applications. If we change variable in the Laravel `.env` file we do not see the variable updated even after reloading the RoadRunner workers - a full daemon restart is required.

I see 2.0.4 introduced some new `.env` functionality - we are not using that.

**Comment by 48d90782** [comment]
@48d90782 Update default value here: https://github.com/spiral/roadrunner-binary/blob/master/internal/cli/root.go#L87, use just empty string. To turn on this feature user should explicitly use the `--dotenv` flag.

**Comment by 48d90782** [comment]
@taylorotwell Feel free to try nightly builds from here without `--dotenv`: https://github.com/spiral/roadrunner-binary/actions/runs/765151263
In the upcoming `2.0.5` you can remove the `--dontenv` flag, by default it will refer to the empty string.
